name: build

on: [push,pull_request]

jobs:
  test-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install yq
        run: |
          sudo snap install yq

      # Either use the Docker container, or the manual setup

      # Docker container
      # - name: Build document in the Metanorma container
      #   env:
      #     METANORMA_DOCKER: metanorma/mn:latest
      #   run: |
      #     make clean all publish

      # Local build
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - name: Update gems
        run: |
          gem install bundler -v "~> 2"
          bundle update --bundler
          bundle install --jobs 4 --retry 3
      - name: Install Metanorma
        run: |
          sudo apt-get install -y libxml2-dev libxslt1-dev libicu-dev zlib1g-dev
          curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | sudo bash
      - name: Metanorma compile
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          make clean all publish
      - name: deploy-to-gh
        if: github.ref == 'refs/heads/master'
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-to-gh-pages.sh | bash
